// Production build: bundle JS (esbuild), copy static files, generate PWA icons + manifest + offline service worker.
import * as esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { makeIcons } from './icons.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIST = path.join(ROOT, 'dist');

export async function build({ dev = false, outdir = DIST, version } = {}) {
  fs.rmSync(outdir, { recursive: true, force: true });
  fs.mkdirSync(outdir, { recursive: true });
  // identifies this exact source tree, so a host and a guest running different builds can be told so
  const src = crypto.createHash('sha1');
  const walkSrc = (d) => { for (const f of fs.readdirSync(d).sort()) { const p = path.join(d, f); fs.statSync(p).isDirectory() ? walkSrc(p) : src.update(fs.readFileSync(p)); } };
  walkSrc(path.join(ROOT, 'js')); walkSrc(path.join(ROOT, 'css')); src.update(fs.readFileSync(path.join(ROOT, 'index.html')));
  const buildId = src.digest('hex').slice(0, 7);
  const result = await esbuild.build({
    entryPoints: { app: path.join(ROOT, 'js/main.js') },
    outdir, bundle: true, format: 'esm', splitting: true, minify: !dev, sourcemap: dev ? 'inline' : false,
    target: ['es2022', 'safari16', 'chrome110', 'firefox110'], metafile: true, legalComments: 'none', logLevel: 'warning',
    define: { 'process.env.NODE_ENV': dev ? '"development"' : '"production"', __BUILD__: JSON.stringify(buildId) },
  });
  // static files
  const copy = (src, dst) => { fs.mkdirSync(path.dirname(path.join(outdir, dst)), { recursive: true }); fs.cpSync(path.join(ROOT, src), path.join(outdir, dst), { recursive: true }); };
  copy('css', 'css'); copy('assets', 'assets');
  // content hash for cache-busting
  const h = crypto.createHash('sha1');
  const walk = (d) => { for (const f of fs.readdirSync(d).sort()) { const p = path.join(d, f); fs.statSync(p).isDirectory() ? walk(p) : h.update(fs.readFileSync(p)); } };
  walk(outdir);
  const hash = (version || h.digest('hex').slice(0, 10));
  let html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  html = html.replace('href="css/style.css"', `href="css/style.css?v=${hash}"`).replace('src="app.js"', `src="app.js?v=${hash}"`);
  fs.writeFileSync(path.join(outdir, 'index.html'), html);
  // icons + manifest
  const icons = await makeIcons(path.join(outdir, 'icons'));
  const manifest = {
    name: 'Snug Isles', short_name: 'Snug Isles', description: 'A cozy two-player island crafting and building game.',
    start_url: './', scope: './', display: 'fullscreen', display_override: ['fullscreen', 'standalone'], orientation: 'landscape', background_color: '#3388dc', theme_color: '#3388dc',
    icons: [{ src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png' }, { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png' }, { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' }],
    categories: ['games'],
  };
  fs.writeFileSync(path.join(outdir, 'manifest.webmanifest'), JSON.stringify(manifest, null, 2));
  fs.writeFileSync(path.join(outdir, '.nojekyll'), '');
  // service worker (precache everything; network-first for the page so updates arrive quickly)
  const files = [];
  const collect = (d, base = '') => { for (const f of fs.readdirSync(d)) { const p = path.join(d, f); const rel = base ? base + '/' + f : f; fs.statSync(p).isDirectory() ? collect(p, rel) : files.push(rel); } };
  collect(outdir);
  const precache = files.filter((f) => f !== 'sw.js' && !f.endsWith('.map')).map((f) => (f === 'index.html' ? './' : f));
  precache.push(`app.js?v=${hash}`, `css/style.css?v=${hash}`);
  const sw = `// generated by tools/build.mjs
const CACHE = 'snug-isles-${hash}';
const PRECACHE = ${JSON.stringify(precache)};
self.addEventListener('install', (e) => { e.waitUntil(caches.open(CACHE).then((c) => Promise.all(PRECACHE.map((u) => c.add(new Request(u, { cache: 'reload' })).catch(() => {})))).then(() => self.skipWaiting())); });
self.addEventListener('activate', (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith('snug-isles-') && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || !req.url.startsWith(self.location.origin)) return;
  const isNav = req.mode === 'navigate';
  if (isNav) { e.respondWith(fetch(req).then((r) => { const cp = r.clone(); caches.open(CACHE).then((c) => c.put('./', cp)); return r; }).catch(() => caches.match('./'))); return; }
  e.respondWith(caches.match(req, { ignoreSearch: false }).then((hit) => hit || fetch(req).then((r) => { if (r.ok) { const cp = r.clone(); caches.open(CACHE).then((c) => c.put(req, cp)); } return r; })));
});
self.addEventListener('message', (e) => { if (e.data === 'skip') self.skipWaiting(); });
`;
  fs.writeFileSync(path.join(outdir, 'sw.js'), sw);
  const sizes = Object.entries(result.metafile.outputs).filter(([k]) => k.endsWith('.js')).map(([k, v]) => `${path.basename(k)} ${(v.bytes / 1024).toFixed(0)}KB`);
  return { hash, sizes, outdir };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const dev = process.argv.includes('--dev');
  const r = await build({ dev });
  console.log(`built ${r.hash} -> dist/  [${r.sizes.join(', ')}]`);
}
