// Serverless "copy/paste code" pairing between two real browsers (no matchmaking server). node tools/e2e-manual.mjs [hostEngine] [guestEngine]
import { chromium, webkit } from 'playwright';
import { startServer } from './serve.mjs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const [hostEng = 'chromium', guestEng = 'webkit'] = process.argv.slice(2);
const { server, url } = await startServer(path.join(ROOT, 'dist'));
const eng = (n) => (n === 'webkit' ? webkit : chromium);
const launchOpts = { args: ['--disable-features=WebRtcHideLocalIpsWithMdns'] };
const hb = await eng(hostEng).launch(hostEng === 'chromium' ? launchOpts : {}), gb = hostEng === guestEng ? hb : await eng(guestEng).launch(guestEng === 'chromium' ? launchOpts : {});
const logs = []; let failed = 0;
const ok = (c, m) => { console.log((c ? '  ✔ ' : '  ✖ ') + m); if (!c) failed++; };
const mk = async (b, name) => { const c = await b.newContext({ viewport: { width: 1180, height: 820 }, deviceScaleFactor: 2 }); const p = await c.newPage(); p.on('pageerror', (e) => logs.push(`[${name}] PAGEERROR: ${e.message}`)); p.on('console', (m) => { if (m.type() === 'error' && !/matchmaking|WebSocket|ERR_CONNECTION/i.test(m.text())) logs.push(`[${name}] console.error: ${m.text()}`); }); return p; };
const host = await mk(hb, 'host'), guest = await mk(gb, 'guest');
console.log(`host=${hostEng} guest=${guestEng}  (matchmaking server deliberately unreachable)`);
const dead = '&peerhost=127.0.0.1&peerport=1&peerpath=/';
await host.goto(url + '?quick=cozy&seed=man' + dead, { waitUntil: 'load' }); await host.waitForTimeout(1500);
await host.evaluate(() => { __snug.profile.name = 'Mochi'; __snug.game.me.name = 'Mochi'; });
await host.evaluate(() => __snug.startHosting(__snug.game));
await host.waitForSelector('textarea.sdp', { timeout: 30000, state: 'attached' });
ok(true, 'host panel shows the manual pairing block even though the matchmaking server is down');
await host.getByText('Manual pairing', { exact: false }).first().click(); await host.getByRole('button', { name: 'Make invite code' }).click();
await host.waitForFunction(() => document.querySelector('textarea.sdp[readonly]').value.length > 50, null, { timeout: 15000 });
const offer = await host.evaluate(() => document.querySelector('textarea.sdp[readonly]').value);
ok(/^[ZR]/.test(offer) && offer.length < 4000, `invite code made (${offer.length} chars)`);

await guest.goto(url + '?x=1' + dead, { waitUntil: 'load' }); await guest.waitForTimeout(1200);
await guest.evaluate(() => { __snug.profile.name = 'Gigi'; __snug.saveProfile(); });
const answer = await guest.evaluate((o) => __snug.manualJoin(o, (m) => { window.__st = m; }), offer);
ok(/^[ZR]/.test(answer) && answer.length < 4000, `answer code made (${answer.length} chars)`);
if (+process.env.PASTE_DELAY_MS) { console.log(`  (a human takes ${+process.env.PASTE_DELAY_MS / 1000}s to carry the answer back…)`); await host.waitForTimeout(+process.env.PASTE_DELAY_MS); }
await host.fill('textarea.sdp:not([readonly])', answer);
await host.getByRole('button', { name: 'Connect', exact: true }).click();
const knock = host.getByRole('button', { name: 'Let them in' });
await knock.waitFor({ timeout: 30000 }).catch(() => {});
await knock.click().catch(() => {});
await guest.waitForFunction(() => __snug.game && __snug.game.mode === 'client', null, { timeout: 60000 }).catch(() => {});
ok(await guest.evaluate(() => __snug.game && __snug.game.mode) === 'client', 'guest entered the host\'s world');
await guest.waitForTimeout(800);
const names = async (p) => p.evaluate(() => [...__snug.game.world.players.values()].filter((q) => q.online).map((q) => q.name).sort());
const hn = await names(host), gn = await names(guest);
ok(hn.includes('Gigi') && hn.includes('Mochi'), `host sees ${hn}`);
ok(gn.includes('Gigi') && gn.includes('Mochi'), `guest sees ${gn}`);
await host.evaluate(() => { const g = __snug.game; g.world.techs.add('carpentry'); const me = g.me; me.inv[3] = { id: 'plank', n: 20 }; me.rev++; const tx = Math.floor(me.x / 16) + 2, ty = Math.floor(me.y / 16) - 2; g.cmd({ c: 'build', bid: 'wall_plank', tx, ty }); window.__w = [tx, ty]; });
await guest.waitForTimeout(700);
const [wx, wy] = await host.evaluate(() => window.__w);
ok(await guest.evaluate(([x, y]) => __snug.game.world.wall[__snug.game.world.idx(x, y)] > 0, [wx, wy]), 'host built a wall and it appears for the guest');
ok(await host.evaluate(() => !!__snug.game.net.hl.clientCount), 'host reports 1 connected partner');
console.log('errors:', logs.length ? '\n' + logs.join('\n') : 'none'); if (logs.length) failed++;
await hb.close(); if (gb !== hb) await gb.close(); server.close();
console.log(failed ? `\n${failed} FAILED` : '\nMANUAL PAIRING WORKS');
process.exit(failed ? 1 : 0);
