// The invite-link flow a partner actually uses: open the link on a fresh device, pick a name, join. node tools/e2e-invite.mjs [hostEngine] [guestEngine]
import { chromium, webkit } from 'playwright';
import { PeerServer } from 'peer';
import { startServer } from './serve.mjs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const [hostEng = 'chromium', guestEng = 'webkit'] = process.argv.slice(2);
const { server, url } = await startServer(path.join(ROOT, 'dist'));
const peerSrv = PeerServer({ port: 9034, path: '/' });
const q = '&peerhost=127.0.0.1&peerport=9034&peerpath=/';
const eng = (n) => (n === 'webkit' ? webkit : chromium);
const opts = { args: ['--disable-features=WebRtcHideLocalIpsWithMdns'] };
const hb = await eng(hostEng).launch(hostEng === 'chromium' ? opts : {}), gb = await eng(guestEng).launch(guestEng === 'chromium' ? opts : {});
let failed = 0; const logs = [];
const ok = (c, m) => { console.log((c ? '  ✔ ' : '  ✖ ') + m); if (!c) failed++; };
const mk = async (b) => { const p = await (await b.newContext({ viewport: { width: 1180, height: 820 }, deviceScaleFactor: 2 })).newPage(); p.on('pageerror', (e) => logs.push('PAGEERROR ' + e.message)); return p; };
const host = await mk(hb), guest = await mk(gb);
await host.goto(url + '?quick=cozy&seed=inv' + q); await host.waitForTimeout(1500);
await host.evaluate(() => { __snug.profile.name = 'Mochi'; __snug.game.me.name = 'Mochi'; });
await host.evaluate(() => __snug.startHosting(__snug.game));
await host.waitForFunction(() => __snug.game.net && __snug.game.net.code, null, { timeout: 25000 });
const link = await host.evaluate(() => __snug.game.net.inviteUrl());
ok(/\?join=[A-Z2-9]{5}/.test(link), 'the invite link carries the room code: ' + link.replace(/^https?:\/\/[^/]+/, ''));
console.log('partner opens the link on a fresh device');
await guest.goto(link.replace(/^https?:\/\/[^/]+\/[^?]*/, url) + q); await guest.waitForTimeout(2500);
ok(await guest.evaluate(() => !!document.querySelector('input[placeholder="Your name"]')), 'the join screen asks for her name');
ok((await guest.evaluate(() => __snug.game && __snug.game.mode)) !== 'client', 'a fresh profile is not auto-joined as "Friend"');
await guest.locator('input[placeholder="Your name"]').fill('Gigi');
await guest.getByRole('button', { name: 'Join!', exact: true }).click();
const knock = host.getByRole('button', { name: 'Let them in' });
await knock.waitFor({ timeout: 30000 }).catch(() => {});
ok(await host.evaluate(() => /Gigi wants to join/.test(document.body.innerText)), 'the host sees "Gigi wants to join your world"');
await knock.click({ timeout: 5000 }).catch(() => {});
await guest.waitForFunction(() => __snug.game && __snug.game.mode === 'client', null, { timeout: 30000 }).catch(() => {});
ok(await guest.evaluate(() => __snug.game && __snug.game.mode) === 'client', 'she is in the world');
console.log('and next time (profile set up) the same link joins by itself');
await guest.evaluate(() => __snug.quitToTitle()); await guest.waitForTimeout(800);
await guest.goto(link.replace(/^https?:\/\/[^/]+\/[^?]*/, url) + q); 
await guest.waitForFunction(() => __snug.game && __snug.game.mode === 'client', null, { timeout: 40000 }).catch(() => {});
ok(await guest.evaluate(() => __snug.game && __snug.game.mode) === 'client', 'second visit: straight in (no approval needed either)');
console.log('errors:', logs.length ? logs : 'none'); if (logs.length) failed++;
await hb.close(); await gb.close(); server.close(); peerSrv.close && peerSrv.close();
console.log(failed ? `\n${failed} FAILED` : '\nINVITE FLOW WORKS'); process.exit(failed ? 1 : 0);
