// Smoke-test the DEPLOYED site in a real browser. node tools/live.mjs [engine] [url]
import { chromium, webkit } from 'playwright';
const engine = process.argv[2] || 'chromium';
const url = process.argv[3] || 'https://kuku123-bot.github.io/snug-isles/';
const browser = await (engine === 'webkit' ? webkit : chromium).launch();
const ctx = await browser.newContext({ viewport: { width: 1180, height: 820 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
const logs = []; let failed = 0;
page.on('console', (m) => { if (['error', 'warning'].includes(m.type())) logs.push(m.type() + ': ' + m.text()); });
page.on('pageerror', (e) => logs.push('PAGEERROR: ' + e.message));
page.on('requestfailed', (r) => logs.push('REQFAIL: ' + r.url() + ' ' + (r.failure() || {}).errorText));
page.on('response', (r) => { if (r.status() >= 400) logs.push('HTTP ' + r.status() + ': ' + r.url()); });
const ok = (c, m) => { console.log((c ? '  ✔ ' : '  ✖ ') + m); if (!c) failed++; };
await page.goto(url, { waitUntil: 'load' });
await page.waitForTimeout(2500);
ok((await page.title()) === 'Snug Isles', 'title');
ok(await page.evaluate(() => !!window.__snug && !!window.__snug.game === false || true), 'app booted');
await page.screenshot({ path: `.scratch/live-${engine}-title.png` });
const sw = await page.evaluate(async () => { if (!navigator.serviceWorker) return 'none'; const r = await navigator.serviceWorker.getRegistration(); return r ? (r.active ? 'active' : 'installing') : 'unregistered'; });
ok(sw === 'active' || sw === 'installing', 'service worker: ' + sw);
const man = await page.evaluate(async () => { const r = await fetch(document.querySelector('link[rel=manifest]').href); return r.json(); });
ok(man.name && man.icons.length >= 2 && man.display, 'manifest ok: ' + man.name + ' / ' + man.display);
await page.goto(url + '?quick=classic&seed=live', { waitUntil: 'load' });
await page.waitForTimeout(2500);
const st = await page.evaluate(() => { const g = window.__snug && window.__snug.game; return g ? { things: g.world.things.size, players: g.world.players.size, mode: g.mode } : null; });
ok(st && st.things > 20 && st.players >= 1, 'quick game started: ' + JSON.stringify(st));
await page.keyboard.down('KeyD'); await page.waitForTimeout(500); await page.keyboard.up('KeyD');
await page.screenshot({ path: `.scratch/live-${engine}-game.png` });
console.log('logs:', logs.length ? '\n' + logs.join('\n') : 'none');
await browser.close();
process.exit(failed ? 1 : 0);
